UDP and Gstreamer

diff --git a/docker/l4t-trt/Dockerfile b/docker/l4t-trt/Dockerfile
--- a/docker/l4t-trt/Dockerfile
+++ b/docker/l4t-trt/Dockerfile
@@ -1,29 +1,68 @@
 ARG ROOT_CONTAINER
 FROM ${ROOT_CONTAINER}
-
 ENV DEBIAN_FRONTEND=noninteractive
-
 RUN apt-get update && apt-get install -y git build-essential rsync libssl-dev libeigen3-dev libglew-dev libglfw3-dev freeglut3-dev libfreetype6-dev libyaml-cpp-dev libpcap-dev libmatio-dev
 RUN apt install -y apt-utils wget && apt install -y --reinstall ca-certificates && wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1.tar.gz && \
     tar xf cmake-3.22.1.tar.gz && \ 
     cd cmake-3.22.1 && \
     ./bootstrap && make -j4 && make install
-
 RUN cmake --version
-# Update cmake for tkdnn compiling
-RUN apt install -y gpg wget && \
-    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null && \
-    echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ bionic main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null && \
-    apt update -y && rm /usr/share/keyrings/kitware-archive-keyring.gpg && \
-    apt install -y kitware-archive-keyring && \
-    apt update -y && apt install -y cmake && cmake --version
-
 RUN apt-get install -y python3-matplotlib python-dev libgdal-dev libcereal-dev python-numpy
 RUN apt-get install -y libgles2-mesa-dev xorg-dev libglu1-mesa-dev
-
 RUN mkdir -p /root/repos
 WORKDIR /root/repos
-
+RUN echo hola
+RUN apt-get update && \
+    apt-get purge -y '*opencv*' || echo "existing OpenCV installation not found" && \
+    apt-get install -y --no-install-recommends \
+          nano \
+          mesa-utils \
+          lsb-release \
+          gstreamer1.0-tools \
+          gstreamer1.0-libav \
+          gstreamer1.0-rtsp \
+          gstreamer1.0-plugins-good \
+          gstreamer1.0-plugins-bad \
+          gstreamer1.0-plugins-ugly \
+          libgstreamer-plugins-base1.0-dev \
+          libgstreamer-plugins-good1.0-dev \
+          libgstreamer-plugins-bad1.0-dev && \
+    if [ `lsb_release --codename --short` != 'bionic' ]; then \
+    apt-get install -y --no-install-recommends \
+          gstreamer1.0-plugins-rtp; \
+    else echo "skipping packages unavailable for Ubuntu 18.04"; fi \
+    && rm -rf /var/lib/apt/lists/* \
+    && apt-get clean
+#
+# install development packages (from dustynv jetson-inference repository)
+#
+RUN apt-get update -y && apt-get install -y --no-install-recommends lsb-release
+RUN add-apt-repository --remove "deb https://apt.kitware.com/ubuntu/ $(lsb_release --codename --short) main" && \
+    apt-get update && \
+    apt-get purge -y '*opencv*' || echo "existing OpenCV installation not found" && \
+    apt-get install -y --no-install-recommends \
+          mesa-utils \
+          lsb-release \
+          gstreamer1.0-tools \
+          gstreamer1.0-libav \
+          gstreamer1.0-rtsp \
+          gstreamer1.0-plugins-good \
+          gstreamer1.0-plugins-bad \
+          gstreamer1.0-plugins-ugly \
+          libgstreamer-plugins-base1.0-dev \
+          libgstreamer-plugins-good1.0-dev \
+          libgstreamer-plugins-bad1.0-dev && \
+    if [ `lsb_release --codename --short` != 'bionic' ]; then \
+    apt-get install -y --no-install-recommends \
+          gstreamer1.0-plugins-rtp; \
+    else echo "skipping packages unavailable for Ubuntu 18.04"; fi \
+    && rm -rf /var/lib/apt/lists/* \
+    && apt-get clean
+# make a copy of this cause it gets purged...
+RUN mkdir -p /usr/local/include/gstreamer-1.0/gst && \
+    cp -r /usr/include/gstreamer-1.0/gst/webrtc /usr/local/include/gstreamer-1.0/gst && \
+    ls -ll /usr/local/include/ && \
+    ls -ll /usr/local/include/gstreamer-1.0/gst/webrtc
 RUN apt-get update -y && apt install -y build-essential \
     unzip \
     pkg-config \
@@ -59,84 +98,29 @@ RUN apt-get update -y && apt install -y build-essential \
     v4l-utils \
     libglm-dev \
     zlib1g-dev
-
 ARG OPENCV_VERSION="4.7.0"
 COPY docker/l4t-trt/build_opencv.sh build_opencv.sh 
 RUN bash build_opencv.sh  ${OPENCV_VERSION} 
-
-# Class edge compiling requirements
-RUN  wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz && \
-     tar xf eigen-3.4.0.tar.gz && cd eigen-3.4.0 && \
-     mkdir build_dir && cd build_dir && cmake .. && make install -j4
-#RUN apt install -y geographiclib-tools
-RUN   wget https://sourceforge.net/projects/geographiclib/files/distrib/GeographicLib-1.52.tar.gz && \
-tar xfpz GeographicLib-1.52.tar.gz && \
-cd GeographicLib-1.52  && \
-mkdir BUILD && \
-cd BUILD && \
-cmake .. && \
-make install -j4
-
-RUN wget https://bootstrap.pypa.io/pip/3.6/get-pip.py && python3 get-pip.py && \
-    python3 -m pip install --upgrade pip && \
-    apt install -y libzmq3-dev && \
-    pip install pytest
-
-RUN git clone https://github.com/pybind/pybind11.git && \
-    cd pybind11 && \
-    mkdir build && \
-    cd build && \
-    cmake .. && \
-    make check -j8 && \
-    make install
-
-
+RUN apt install -y libzmq3-dev
 ENV AAA=BBB
 RUN echo "BBBB"
-# RUN cd /root/repos && git clone https://pat:ZBDrnj-dzZEUdBAFz6KF@gitlab.bsc.es/ppc/benchmarks/smart-city/camera-edge.git -b master
-RUN mkdir -p /root/repos/camera-edge
+RUN mkdir -p /root/repos/
 RUN mkdir -p /root/b2drop
-COPY . /root/repos/camera-edge
+RUN cd /root/repos && git clone https://pat:ZBDrnj-dzZEUdBAFz6KF@gitlab.bsc.es/ppc/benchmarks/smart-city/camera-edge.git -b master
 WORKDIR /root/repos/camera-edge
-RUN wget https://github.com/glfw/glfw/releases/download/3.3/glfw-3.3.zip && unzip glfw-3.3.zip && mkdir -p glfw-3.3/build && cd glfw-3.3/build && cmake .. && make -j4 && make install
-RUN git submodule add https://gitlab.bsc.es/ppc-bsc/software/masa_protocol.git ./masa_protocol
-RUN git submodule update --init --recursive 
-# RUN git submodule add https://gitlab.bsc.es/ppc/benchmarks/ai/trt-detect.git ./trt-detect
-# RUN git submodule update --init --recursive 
-
-# RUN cd class-edge && \
-#     git submodule add https://gitlab.bsc.es/ppc-bsc/masa_protocol ./masa_protocol && \
-#     git submodule update --init --recursive 
-
-RUN mkdir build && cd build && \
-    cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -Wno-dev .. && \
-    make
-# # Creating .rt file of DNN used
-# RUN apt install -y curl
-# RUN cd build/tkDNN && \
-#     mkdir yolo4_berkeley && \
-#     curl -tlsv1 -C - https://cloud.hipert.unimore.it/s/nkWFa5fgb4NTdnB/download --output yolo4_berkeley/weights.zip --user user:pass -O --retry 999 --retry-max-time 0 && \
-#     unzip yolo4_berkeley/weights.zip -d yolo4_berkeley && \ 
-#     rm yolo4_berkeley/weights.zip && \
-#     ./test_yolo4_berkeley && \
-#     mv yolo4_berkeley ../
-
+RUN git clone https://pat:4dvKs5a1DtGsoeVfFxci@gitlab.bsc.es/ppc/benchmarks/ai/trt-detect.git -b Vicente-Masip-CU-86bz8v5k1
 RUN apt-get update -y && apt install -y gdb
 
-# # COMPSS added in this dockerfile for PAI Project. 
-# RUN python3 -m pip install dataclay pymap3d zmq requests pygeohash geolib 
-# RUN apt install -y libeigen3-dev libflann-dev python3-matplotlib python-dev python-dev libflann-dev
-# RUN ln -s /usr/include/eigen3/Eigen /usr/include/Eigen
-# WORKDIR /root/repos/
-# RUN git clone --depth 1 --branch udpsockets https://github.com/class-euproject/COMPSs-obstacle-detection.git &&  \
-#     cd COMPSs-obstacle-detection && \
-#     git submodule init && \
-#     git submodule update && \
-#     cd ./tracker_CLASS/ && \
-#     mkdir build && \
-#     cd build && \
-#     cmake ../ && \
-#     make -j && \
-#     mv track*.so ../../track.so
-# # cd class-edge/build/tkDNN/ && ./demo 1 2404 5559 -1 0 0 0.5 &
-# COPY tracker.py ./COMPSs-obstacle-detection/
+# RUN echo hola
+# RUN ls -laRt .
+# COPY ./CMakeLists.txt /root/repos/camera-edge/CMakeLists.txt
+# RUN rm -rf src include
+# COPY ./src /root/repos/camera-edge/src
+# COPY ./include /root/repos/camera-edge/include
+# COPY .gitmodules /root/repos/camera-edge/
+# RUN cat CMakeLists.txt
+# RUN ls /usr/lib/aarch64-linux-gnu/libnv*
+# RUN apt-get update -y && apt install -y gdb
+# RUN mkdir ./build && cd build && \
+#     cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -Wno-dev .. && \
+#     make
